---

- name: Run on localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
  
  - name: Install Programs
    apt:
      deb: "{{item}}"
    with_items: "{{programs}}"
  
  - name: Install Development Packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items: "{{dev_pkgs}}"

  - name: Install Python Tools
    pip:
      executable: "{{ item[0] }}"
      name: "{{ item[1] }}"
    with_nested: 
      - ['pip', 'pip3']
      - "{{python_tools}}"

  - name: Install Web Scraping Tools
    pip:
      executable: "{{ item[0] }}"
      name: "{{ item[1] }}"
    with_nested: 
      - ['pip', 'pip3']
      - "{{python_scraping_tools}}"

  - name: Install Data Science Tools
    pip:
      executable: "{{ item[0] }}"
      name: "{{ item[1] }}"
    with_nested: 
      - ['pip', 'pip3']
      - "{{python_data_science_tools}}"

  - name: Install Deep Learning Tools
    pip:
      executable: "{{ item[0] }}"
      name: "{{ item[1] }}"
    with_nested: 
      - ['pip', 'pip3']
      - "{{python_deep_learning}}"

  - name: Install Cryptocurrency Tools
    pip:
      executable: "{{ item[0] }}"
      name: "{{ item[1] }}"
    with_nested: 
      - ['pip', 'pip3']
      - "{{python_cryptocurrency}}"

## Install DevOps Tools
  - name: Install DevOps Tools
    include_role:
      name: install-devops