---  # roles/install-devops/tasks/main.yaml

- name: Is Docker Installed?
  stat:
    path: /usr/bin/docker
  register: ret_docker

- name: Install Docker CE
  block:
    - name: Add GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: Add Docker Repository to APT sources
      shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - name: Update Packages to grab newly added repo
      shell: sudo apt-get update
    - name: Install Docker
      shell: sudo apt-get install -y docker-ce
  when: not ret_docker.stat.exists

- name: Is Packer Installed?
  stat:
    path: /usr/bin/packer
  register: ret_packer

- name: Install Packer
  block:
    - name: Download Packer Binary
      shell: wget -O packer-binary.zip https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip?_ga=2.106922755.1420311161.1517697788-1645665399.1517697788
    - name: Unzip Packer
      shell: unzip packer-binary.zip -d /usr/bin/
    - name: Clean Up
      shell: rm packer-binary.zip
  when: not ret_packer.stat.exists